/**
 * The monthly card processing statement from Global Payments (Heartland), read as the fees it records.
 *
 * The owner, 15 September 2026: *"you will get this statement once monthly to account for credit card
 * fees. it will come from jdarrah@wwfppa.com, we need to be ready to receive and handle correctly!!!"*
 *
 * The statement is a 7-page PDF generated by OpenText Exstream. `pdfText` returns it with every glyph
 * placed separately and so without spaces — "TotalDeposits....$94,529.08" — which is why every pattern
 * here reads the run-together form.
 *
 * ── What it says, from the August 2026 statement ──
 *
 *   Total Deposits $94,529.08, Total Fees $4,778.73.
 *   Fees by section — Visa, Mastercard, American Express and Discover pass-through interchange, and
 *   "GP Processing Fees", Global Payments' own charges — each with a subtotal.
 *   A Deposit Detail table: one row per batch, "000149 T $4,482.40 - $4,482.40 -", its batch date, and
 *   "ACH 08/01/2026 --- $4,482.40". The daily discount column is "-": nothing is held back from a
 *   deposit. Each batch reaches the bank whole, the next day, weekends included.
 *   And one row "Fees T 08/31/2026 --- ($4,778.73)": the month's fees, taken by a single auto-debit.
 *
 * ── Where it goes in the books ──
 *
 * **Fees only.** An expense in the statement month, paid on the auto-debit date the statement prints.
 *
 * **Never the deposits.** They are the same money as the daily card batch reports, which are already
 * banked as counter takings. They are read for one purpose: to check that every batch the processor
 * settled has a batch report on file, because the statement is the only independent count of them.
 *
 * ── What it refuses ──
 *
 * A statement whose own figures do not agree: the fee sections against the total, the deposit rows
 * against the total, the processing summary against the total, the auto-debit against the fees.
 * And a deposit row with a daily discount in it — that would mean fees had started being netted from
 * deposits, which changes how every batch matches the bank, and must be seen rather than absorbed.
 *
 * Pure.
 */

export type CardStatement = {
  merchantNumber: string;
  dbaName: string | null;
  periodFrom: string;
  periodTo: string;
  totalDepositsCents: number;
  totalFeesCents: number;
  feeSections: { name: string; cents: number }[];
  /** The card networks' interchange and assessments, passed through at cost. */
  passThroughCents: number;
  /** Global Payments' own charges. */
  processorCents: number;
  salesCents: number | null;
  refundsCents: number | null;
  transactions: number | null;
  deposits: { sequence: string; batchDate: string; amountCents: number; achDate: string | null }[];
  feeDebit: { on: string; cents: number };
  says: string;
};

/**
 * The invoice number every statement's fee bill is filed under: `GP-<merchant number>-<period end>`.
 * One bill per merchant per month, so a statement forwarded twice books once, and the bank's fee debit
 * can find the bill it pays.
 */
export const CARD_STATEMENT_BILL = "GP-";
export const cardStatementBillNumber = (s: Pick<CardStatement, "merchantNumber" | "periodTo">) => `${CARD_STATEMENT_BILL}${s.merchantNumber}-${s.periodTo}`;

export type CardStatementRead = { ok: true; statement: CardStatement } | { ok: false; why: string };

const MONEY = String.raw`\$?\(?\$?([\d,]+\.\d{2})\)?`;
const cents = (v: string) => Math.round(Number(v.replace(/[$,()]/g, "")) * 100);
const iso = (mdy: string) => {
  const [m, d, y] = mdy.split("/");
  return `${y}-${m.padStart(2, "0")}-${d.padStart(2, "0")}`;
};
const money = (c: number) => `$${(c / 100).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

/** Whether PDF text is this statement. Checked against the run-together lines `pdfText` returns. */
export function looksLikeCardStatement(text: string): boolean {
  const t = text.replace(/\s+/g, "");
  return /MerchantStatement/i.test(t) && /StatementPeriod:\d{2}\/\d{2}\/\d{4}-\d{2}\/\d{2}\/\d{4}/i.test(t) && /GlobalPayments|Heartland/i.test(t);
}

export function readCardStatement(text: string): CardStatementRead {
  if (!looksLikeCardStatement(text)) return { ok: false, why: "Not a Global Payments merchant statement." };
  const lines = text.split(/\r?\n/).map((l) => l.replace(/\s+/g, "")).filter(Boolean);
  const find = (re: RegExp) => {
    for (const l of lines) {
      const m = re.exec(l);
      if (m) return m;
    }
    return null;
  };

  const period = find(/StatementPeriod:(\d{2}\/\d{2}\/\d{4})-(\d{2}\/\d{2}\/\d{4})/i);
  const merchant = find(/MerchantNumber:(\d{8,})/i);
  const dba = find(/DBAName:(.+)$/i);
  const deposits = find(new RegExp(String.raw`^TotalDeposits\.*${MONEY}$`, "i"));
  const fees = find(new RegExp(String.raw`^TotalFees\.*${MONEY}$`, "i"));
  if (!period || !merchant || !deposits || !fees) {
    const missing = [!period && "the statement period", !merchant && "the merchant number", !deposits && "total deposits", !fees && "total fees"].filter(Boolean);
    return { ok: false, why: `The statement was recognised but ${missing.join(", ")} could not be read.` };
  }
  const totalDepositsCents = cents(deposits[1]);
  const totalFeesCents = cents(fees[1]);

  /*
   * Fee sections: each heading, paired with the next "Subtotal" after it. A section can run over a page
   * break with the column headings repeated inside it, which is why it is the next subtotal and not the
   * next line.
   */
  const feeSections: CardStatement["feeSections"] = [];
  for (let i = 0; i < lines.length; i++) {
    const heading = /^(.+?(?:Pass-thruInterchange&Fees|Pass-thruFees)|GPProcessingFees)$/i.exec(lines[i]);
    if (!heading) continue;
    for (let j = i + 1; j < lines.length; j++) {
      const sub = new RegExp(String.raw`^Subtotal${MONEY}$`, "i").exec(lines[j]);
      if (sub) {
        feeSections.push({ name: heading[1].replace(/Pass-thru.*$/i, "").replace(/^GPProcessingFees$/i, "Global Payments processing"), cents: cents(sub[1]) });
        break;
      }
      if (/Pass-thru|^GPProcessingFees$/i.test(lines[j])) break;
    }
  }
  const processorCents = feeSections.filter((s) => /Global Payments/.test(s.name)).reduce((n, s) => n + s.cents, 0);
  const passThroughCents = feeSections.reduce((n, s) => n + s.cents, 0) - processorCents;

  /* Processing summary totals: "2,430$94,678.942($149.86)$94,529.08$38.96" — count, sales, refunds, net, ticket. */
  let salesCents: number | null = null, refundsCents: number | null = null, transactions: number | null = null, netCents: number | null = null;
  const summaryAt = lines.findIndex((l) => /^ProcessingSummary-SettledbyGP/i.test(l));
  if (summaryAt >= 0) {
    for (let i = summaryAt; i < Math.min(lines.length, summaryAt + 40); i++) {
      if (/^Totals$/i.test(lines[i]) && i > 0) {
        const t = /^([\d,]+)\$([\d,]+\.\d{2})(\d+)\(\$([\d,]+\.\d{2})\)\$([\d,]+\.\d{2})\$[\d,]+\.\d{2}$/.exec(lines[i - 1])
          ?? /^([\d,]+)\$([\d,]+\.\d{2})(\d+)-*\$([\d,]+\.\d{2})\$[\d,]+\.\d{2}$/.exec(lines[i - 1]);
        if (t && t.length === 6) {
          transactions = Number(t[1].replace(/,/g, ""));
          salesCents = cents(t[2]);
          refundsCents = -cents(t[4]);
          netCents = cents(t[5]);
        }
        break;
      }
    }
  }

  /* Deposit detail: a batch row, then its batch date, then its ACH line — with page furniture possibly between. */
  const depositRows: CardStatement["deposits"] = [];
  const problems: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    const row = /^(\d{6})T\$([\d,]+\.\d{2})(-|\(?\$[\d,]+\.\d{2}\)?)\$([\d,]+\.\d{2})-$/.exec(lines[i]);
    if (!row) continue;
    if (row[3] !== "-") problems.push(`batch ${row[1]} has ${row[3]} held back as a daily discount — fees are now being netted from deposits`);
    const dateLine = lines.slice(i + 1, i + 3).find((l) => /^\d{2}\/\d{2}\/\d{4}$/.test(l));
    const ach = lines.slice(i + 1, i + 25).map((l) => /^ACH(\d{2}\/\d{2}\/\d{4})/i.exec(l)).find(Boolean) ?? null;
    if (!dateLine) {
      problems.push(`batch ${row[1]} has no batch date beside it`);
      continue;
    }
    depositRows.push({ sequence: row[1], batchDate: iso(dateLine), amountCents: cents(row[4]), achDate: ach ? iso(ach[1]) : null });
  }

  const debit = find(/^FeesT(\d{2}\/\d{2}\/\d{4})-*\(\$([\d,]+\.\d{2})\)$/i);

  const sectionSum = feeSections.reduce((n, s) => n + s.cents, 0);
  const depositSum = depositRows.reduce((n, d) => n + d.amountCents, 0);
  if (feeSections.length === 0) problems.push("no fee sections were read");
  else if (sectionSum !== totalFeesCents) problems.push(`the fee sections come to ${money(sectionSum)}`);
  if (depositRows.length === 0) problems.push("no deposit rows were read");
  else if (depositSum !== totalDepositsCents) problems.push(`the deposit rows come to ${money(depositSum)}`);
  if (netCents !== null && netCents !== totalDepositsCents) problems.push(`the processing summary nets to ${money(netCents)}`);
  if (!debit) problems.push("the fee auto-debit line could not be read");
  else if (cents(debit[2]) !== totalFeesCents) problems.push(`the fee auto-debit is ${money(cents(debit[2]))}`);
  if (problems.length) {
    return { ok: false, why: `Statement ${merchant[1]} for ${iso(period[1])} to ${iso(period[2])} shows deposits of ${money(totalDepositsCents)} and fees of ${money(totalFeesCents)}, but ${problems.join("; ")}. Nothing was recorded.` };
  }

  const rate = totalDepositsCents > 0 ? (totalFeesCents / totalDepositsCents) * 100 : 0;
  return {
    ok: true,
    statement: {
      merchantNumber: merchant[1],
      dbaName: dba ? dba[1] : null,
      periodFrom: iso(period[1]),
      periodTo: iso(period[2]),
      totalDepositsCents,
      totalFeesCents,
      feeSections,
      passThroughCents,
      processorCents,
      salesCents,
      refundsCents,
      transactions,
      deposits: depositRows,
      feeDebit: { on: iso(debit![1]), cents: totalFeesCents },
      says:
        `Card processing statement for ${iso(period[1])} to ${iso(period[2])}: ${money(totalFeesCents)} of fees on ${money(totalDepositsCents)} of card deposits ` +
        `(${rate.toFixed(2)}%) — ${money(passThroughCents)} passed through from the card networks and ${money(processorCents)} charged by Global Payments — ` +
        `taken by auto-debit on ${iso(debit![1])}. ${depositRows.length} batches deposited.`,
    },
  };
}
